server:
  port: ${TRANSACTION_SERVICE_PORT:8084}

spring:
  application:
    name: transactions-service
  
  # Configuration Base de Données
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eventy_transactions}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  # JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # Sécurité (Resource Server pour valider les JWT)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/eventy-realm}

# Client Eureka pour trouver les autres services (ticket-service)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Configuration des logs pour voir les requêtes Feign
logging:
  level:
    com.polytech.transactionservice.client: DEBUG